package ryoryo.polishedstone.util;

public class LibRenderId {
	public static final int RENDER_STANDARD_BLOCK = 0;
	public static final int RENDER_BLOCK_LIQUID = 4;
	public static final int RENDER_BLOCK_LOG = 31;
	public static final int RENDER_CROSSED_SQUARE = 1;
	public static final int RENDER_BLOCK_DOUBLE_PLANT = 40;
	public static final int RENDER_BLOCK_TORCH = 2;
	public static final int RENDER_BLOCK_VINE = 20;
	public static final int RENDER_BLOCK_FENCE = 11;
	public static final int RENDER_BLOCK_QUARTZ = 39;
	public static final int RENDER_BLOCK_REDSTONE_WIRE = 5;
	public static final int RENDER_BLOCK_CACTUS = 13;
	public static final int RENDER_BLOCK_MINECART_TRACK = 9;
	public static final int RENDER_BLOCK_STEM = 19;
	public static final int RENDER_BLOCK_LILY_PAD = 23;
	public static final int RENDER_BLOCK_CROPS = 6;
	public static final int RENDER_BLOCK_FIRE = 3;
	public static final int RENDER_BLOCK_LADDER = 8;
	public static final int RENDER_BLOCK_DOOR = 7;
	public static final int RENDER_BLOCK_STAIRS = 10;
	public static final int RENDER_BLOCK_DRAGON_EGG = 27;
	public static final int RENDER_BLOCK_WALL = 32;
	public static final int RENDER_BLOCK_LEVER = 12;
	public static final int RENDER_BLOCK_TRIP_WIRE_SOURCE = 29;
	public static final int RENDER_BLOCK_TRIP_WIRE = 30;
	public static final int RENDER_BLOCK_BED = 14;
	public static final int RENDER_BLOCK_REPEATER = 15;
	public static final int RENDER_BLOCK_REDSTONE_DIODE = 36;
	public static final int RENDER_BLOCK_REDSTONE_COMPARATOR = 37;
	public static final int RENDER_PISTON_BASE = 16;
	public static final int RENDER_PISTON_EXTENSION = 17;
	public static final int RENDER_BLOCK_PANE = 18;
	public static final int RENDER_BLOCK_STAINED_GLASS_PANE = 41;
	public static final int RENDER_BLOCK_FENCE_GATE = 21;
	public static final int RENDER_BLOCK_CAULDRON = 24;
	public static final int RENDER_BLOCK_FLOWERPOT = 33;
	public static final int RENDER_BLOCK_ANVIL = 35;
	public static final int RENDER_BLOCK_BREWING_STAND = 25;
	public static final int RENDER_BLOCK_END_PORTAL_FRAME = 26;
	public static final int RENDER_BLOCK_COCOA = 28;
	public static final int RENDER_BLOCK_BEACON = 34;
	public static final int RENDER_BLOCK_HOPPER = 38;
}
